### ISSUE TITLE
should {label} be a string input?

### ISSUE THREAD

**Issue by Ellen102** [scratch4d/scratch-LN#69]
`{some text}` is not allowed. 
The tokens are LCurlyBracket, Label, RCurlyBracket. This combination does not occur anywhere.
Why not consider it as a string input?
So {text}  will be the same as {"text"} and "text".

**Comment by pdawyndt** [comment]
Agree since Scratch itself does not make a real distinction between numbers and strings. I see the Scratch blocks themselves know when a number is expected. 

'''
neem {tien} stappen
'''

cannot be entered in the Graphical Scratch interface, so at least a warning should be given in this case.

Would you use a regex to discriminate numbers from strings? I guess both ints and floats are allowed. What about scientific notation?

**Comment by Ellen102** [comment]
It is possible to differentiate at the level of the lexer or do a check in the visitor. I am not sure yet what is the best. As far as I see no scientific notation. I added the warning to the todo list in issue #61 so I can close this issue.
The parser allows { Label } and the visitor makes a text input for this.
